"""
Project 09 - Train CNN for Male/Female Eye Detection
=====================================================
Trains a small CNN to classify eye images as male or female.
Uses synthetic dataset generated by create_dummy_dataset.py.
"""
import os
import numpy as np

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
import cv2

# === 1. Load Dataset =====================================================
DATASET_DIR = os.path.join(os.path.dirname(__file__), "dataset")
IMG_SIZE = 64
CLASSES = ["female", "male"]

if not os.path.exists(DATASET_DIR):
    print("[INFO] Dataset not found. Generating dummy dataset first ...")
    import create_dummy_dataset
    create_dummy_dataset.main()

images, labels = [], []
for label_idx, cls in enumerate(CLASSES):
    cls_dir = os.path.join(DATASET_DIR, cls)
    if not os.path.isdir(cls_dir):
        continue
    for fname in os.listdir(cls_dir):
        fpath = os.path.join(cls_dir, fname)
        img = cv2.imread(fpath, cv2.IMREAD_GRAYSCALE)
        if img is None:
            continue
        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
        images.append(img)
        labels.append(label_idx)

X = np.array(images, dtype=np.float32).reshape(-1, IMG_SIZE, IMG_SIZE, 1) / 255.0
y = np.array(labels, dtype=np.float32)

print(f"[DATA] Loaded {len(X)} images")

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# === 2. Build CNN ========================================================
model = keras.Sequential([
    layers.Input(shape=(IMG_SIZE, IMG_SIZE, 1)),
    layers.Conv2D(32, (3, 3), activation="relu"),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(64, (3, 3), activation="relu"),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(64, (3, 3), activation="relu"),
    layers.MaxPooling2D((2, 2)),

    layers.Flatten(),
    layers.Dense(128, activation="relu"),
    layers.Dropout(0.3),
    layers.Dense(1, activation="sigmoid")
])

model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
model.summary()

# === 3. Train ============================================================
print("\n[TRAIN] Training ...")
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=20,
    batch_size=16,
    verbose=1
)

# === 4. Evaluate =========================================================
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
print(f"\n[RESULT] Test Accuracy : {test_acc:.4f}")
print(f"[RESULT] Test Loss     : {test_loss:.4f}")

# === 5. Save =============================================================
model.save("eye_cnn_model.h5")
print("\n[OK] Model saved as eye_cnn_model.h5")
